In [ ]:
#1. Write a Program to implement Multiple Perceptron Model.

import tensorflow as tf
from tensorflow.keras import layers, models

# Define the MLP model
def create_mlp(input_size, hidden_sizes, output_size):
    model = models.Sequential()
    model.add(layers.InputLayer(input_shape=(input_size,)))
    
    for hidden_size in hidden_sizes:
        model.add(layers.Dense(hidden_size, activation='relu'))
    
    model.add(layers.Dense(output_size, activation='softmax'))
    
    return model

# Example usage
# Define the model architecture
input_size = 10
hidden_sizes = [64, 32]
output_size = 2

# Create the MLP model
mlp_model = create_mlp(input_size, hidden_sizes, output_size)

# Display the model summary
mlp_model.summary()


In [2]:
# 2. Write a Program to implement XOR with backpropagation algorithm.

import numpy as np

class SimplePerceptron:
    def __init__(self, input_size, hidden_size, output_size):
    # Initialize weights and biases with random values
        self.weights_input_hidden = np.random.rand(input_size, hidden_size)
        self.bias_hidden = np.zeros((1, hidden_size))
        self.weights_hidden_output = np.random.rand(hidden_size, output_size)
        self.bias_output = np.zeros((1, output_size))
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    def forward(self, inputs):
        # Forward pass through the network
        self.hidden_layer_activation = self.sigmoid(np.dot(inputs, self.weights_input_hidden
    ) + self.bias_hidden)
        self.output_layer_activation = self.sigmoid(np.dot(self.hidden_layer_activation,
    self.weights_hidden_output) + self.bias_output)
        
        return self.output_layer_activation
    
    def backward(self, inputs, targets, learning_rate):
        # Backward pass through the network
        
        # Calculate output layer error and delta
        output_layer_error = targets - self.output_layer_activation
        output_layer_delta = output_layer_error * self.sigmoid_derivative(self.
    output_layer_activation)
        
        # Calculate hidden layer error and delta
        hidden_layer_error = output_layer_delta.dot(self.weights_hidden_output.T)
        hidden_layer_delta = hidden_layer_error * self.sigmoid_derivative(self.
    hidden_layer_activation)
        
        # Update weights and biases
        self.weights_hidden_output += self.hidden_layer_activation.T.dot(output_layer_delta) * learning_rate
        self.bias_output += np.sum(output_layer_delta, axis=0, keepdims=True) * learning_rate
    
        self.weights_input_hidden += inputs.T.dot(hidden_layer_delta) * learning_rate
        self.bias_hidden += np.sum(hidden_layer_delta, axis=0, keepdims=True) * learning_rate
    
    def train(self, inputs, targets, epochs, learning_rate):
        for epoch in range(epochs):
            # Forward and backward pass for each training example
            for i in range(len(inputs)):
                input_data = np.array([inputs[i]])
                target_data = np.array([targets[i]])
                
            # Forward pass
            output = self.forward(input_data)
            
            # Backward pass
            self.backward(input_data, target_data, learning_rate)
            
        # Print the mean squared error for every 100 epochs
            if epoch % 100 == 0:
                mse = np.mean(np.square(targets - self.forward(inputs)))
                print(f"Epoch {epoch}, Mean Squared Error: {mse}")
    
# Example usage
if __name__ == "__main__":
    # Define the dataset (XOR problem)
    inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    targets = np.array([[0], [1], [1], [0]])
    
    # Create a simple perceptron model
    model = SimplePerceptron(input_size=2, hidden_size=4, output_size=1)
    
    # Train the model
    model.train(inputs, targets, epochs=1000, learning_rate=0.1)
    
    # Test the trained model
    test_inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
    predictions = model.forward(test_inputs)
    print("\nPredictions:")
    print(predictions)

Epoch 0, Mean Squared Error: 0.3481189441822641
Epoch 100, Mean Squared Error: 0.317565807341952
Epoch 200, Mean Squared Error: 0.3765889304131777
Epoch 300, Mean Squared Error: 0.4012494567088313
Epoch 400, Mean Squared Error: 0.41531681676325444
Epoch 500, Mean Squared Error: 0.42465913864237154
Epoch 600, Mean Squared Error: 0.4314319448899343
Epoch 700, Mean Squared Error: 0.4366292666595858
Epoch 800, Mean Squared Error: 0.4407797020436551
Epoch 900, Mean Squared Error: 0.4441932018767713

Predictions:
[[0.06905908]
 [0.05483498]
 [0.05775876]
 [0.04721384]]


In [3]:
#3. Write a Program to implement Union, Intersection and Complement operations in fuzzy set.

Z = {}

def union(A, B):
    for x in A and B:
        Z[x] = max(A[x], B[x])
    return Z

def intersection(A, B):
    for x in A and B:
        Z[x] = min(A[x], B[x])
    return Z

def compliment(X):
    for x in X:
        Z[x] = round(1 - X[x],2)
    return Z

def get_membership_value(key):
    while True:
     
        value = float(input(f"Enter the Membership value (between 0 and 1) for {key}: "))
        if 0 <= value <= 1:
            return value
        else:
            print("Invalid input. Please enter a value between 0 and 1.")
                
A = {}
B = {}

no_items_A = int(input("Enter the number of elements for fuzzy set A: "))
for _ in range(no_items_A):
    key = input("Enter the crispy set elements for A: ")
    value = get_membership_value(key)
    A[key] = value

no_items_B = int(input("Enter the number of elements for fuzzy set B: "))
for _ in range(no_items_B):
    key = input("Enter the crispy set elements for B: ")
    value = get_membership_value(key)
    B[key] = value


print("\nResults:")
print("\nA : ",A)
print("\nB : ",B)
print(f"\nA UNION B: {union(A, B)}")
print(f"\nA INTERSECTION B: {intersection(A, B)}")
print(f"\nCOMPLIMENT OF A: {complement(A)}")
print(f"\nCOMPLIMENT OF B: {complement(B)}")


Enter the number of elements for fuzzy set A: 3
Enter the crispy set elements for A: a
Enter the Membership value (between 0 and 1) for a: 0.7
Enter the crispy set elements for A: b
Enter the Membership value (between 0 and 1) for b: 0.8
Enter the crispy set elements for A: c
Enter the Membership value (between 0 and 1) for c: 0.1
Enter the number of elements for fuzzy set B: 3
Enter the crispy set elements for B: a
Enter the Membership value (between 0 and 1) for a: 0.4
Enter the crispy set elements for B: b
Enter the Membership value (between 0 and 1) for b: 0.6
Enter the crispy set elements for B: c
Enter the Membership value (between 0 and 1) for c: 0.2

Results:

A :  {'a': 0.7, 'b': 0.8, 'c': 0.1}

B :  {'a': 0.4, 'b': 0.6, 'c': 0.2}

A UNION B: {'a': 0.7, 'b': 0.8, 'c': 0.2}

A INTERSECTION B: {'a': 0.4, 'b': 0.6, 'c': 0.1}

COMPLIMENT OF A: {'a': 0.3, 'b': 0.2, 'c': 0.9}

COMPLIMENT OF B: {'a': 0.6, 'b': 0.4, 'c': 0.8}


In [2]:
# 4. Write a program to implement De-Morgan’s Law in Fuzzy sets.

Z = {}

def union(A, B):
    Z = {}
    for x in A and B:
        Z[x] = max(A[x],B[x])
    return Z

def complement(X):
    Z = {}
    for x in X:
        Z[x] = round(1 - X[x], 2)
    return Z

def intersection(A, B):
    for x in A and B:
        Z[x] = min(A[x], B[x])
    return Z

def get_membership_value(key):
    while True:
     
        value = float(input(f"Enter the Membership value (between 0 and 1) for {key}: "))
        if 0 <= value <= 1:
            return value
        else:
            print("Invalid input. Please enter a value between 0 and 1.")
                
A = {}
B = {}

no_items_A = int(input("Enter the number of elements for fuzzy set A: "))
for _ in range(no_items_A):
    key = input("Enter the crispy set elements for A: ")
    value = get_membership_value(key)
    A[key] = value

no_items_B = int(input("Enter the number of elements for fuzzy set B: "))
for _ in range(no_items_B):
    key = input("Enter the crispy set elements for B: ")
    value = get_membership_value(key)
    B[key] = value

# Applying De Morgan's law
LHS = complement(union(A, B))
RHS = intersection(complement(A), complement(B))

print("\nFuzzy Set A : ", A)
print("\nFuzzy Set B : ", B)
print("\nLHS (A U B)':", LHS)
print("\nRHS (A' ∩ B') : ", RHS)

if LHS == RHS:
    print("\nDe Morgan's law is proved \n Since {} = {}".format(LHS, RHS))
else:
    print("De Morgan's law is not proved")


Enter the number of elements for fuzzy set A: 3
Enter the crispy set elements for A: a
Enter the Membership value (between 0 and 1) for a: 0.7
Enter the crispy set elements for A: b
Enter the Membership value (between 0 and 1) for b: 0.8
Enter the crispy set elements for A: c
Enter the Membership value (between 0 and 1) for c: 0.1
Enter the number of elements for fuzzy set B: 3
Enter the crispy set elements for B: a
Enter the Membership value (between 0 and 1) for a: 0.4
Enter the crispy set elements for B: b
Enter the Membership value (between 0 and 1) for b: 0.6
Enter the crispy set elements for B: c
Enter the Membership value (between 0 and 1) for c: 0.2

Fuzzy Set A :  {'a': 0.7, 'b': 0.8, 'c': 0.1}

Fuzzy Set B :  {'a': 0.4, 'b': 0.6, 'c': 0.2}

LHS (A U B)': {'a': 0.3, 'b': 0.2, 'c': 0.8}

RHS (A' ∩ B') :  {'a': 0.3, 'b': 0.2, 'c': 0.8}

De Morgan's law is proved 
 Since {'a': 0.3, 'b': 0.2, 'c': 0.8} = {'a': 0.3, 'b': 0.2, 'c': 0.8}


In [2]:
# 5 Write a program to implement Fuzzy Relations(Max-Min composition)

import numpy as np
def max_min_composition(R, S):
    result = np.zeros((R.shape[0], S.shape[1]))
    
    for i in range(R.shape[0]):
        for j in range(S.shape[1]):
            max_min = 0
            for k in range(R.shape[1]):
                max_min = max(max_min, min(R[i, k], S[k, j]))
            result[i, j] = max_min
    return result

R = np.array([[0.7, 0.6], [0.8, 0.3]])
S = np.array([[0.8, 0.1, 0.4], [0.5, 0.6, 0.7]])

result = max_min_composition(R, S)
print("Result of Max-min Composition:")
print(result)


Result of Max-min Composition:
[[0.7 0.6 0.6]
 [0.8 0.3 0.4]]
